// Deliberately narrow Three.js surface shared by the two home-page scenes.
// Importing the package namespace from a dynamic import retained every Three
// export in production. This facade lets Rollup keep only the constructors and
// constants the river and About field actually use, plus addon dependencies.
export {
  ACESFilmicToneMapping,
  AmbientLight,
  Box3,
  BufferAttribute,
  BufferGeometry,
  ClampToEdgeWrapping,
  Color,
  DirectionalLight,
  EdgesGeometry,
  FogExp2,
  Group,
  HemisphereLight,
  IcosahedronGeometry,
  ImageBitmapLoader,
  LineBasicMaterial,
  LinearFilter,
  LineSegments,
  MathUtils,
  Mesh,
  MeshBasicMaterial,
  MeshStandardMaterial,
  NoColorSpace,
  Object3D,
  PerspectiveCamera,
  Plane,
  PlaneGeometry,
  PMREMGenerator,
  Points,
  PointsMaterial,
  Raycaster,
  RepeatWrapping,
  Scene,
  SRGBColorSpace,
  Texture,
  TextureLoader,
  Timer,
  Vector2,
  Vector3,
  WebGLRenderer,
} from 'three';
