from typing import Any, Callable, Protocol

class DocumentLoader(Protocol):
    def __call__(self, url: str, options: dict[str, Any] | None = ...) -> dict[str, Any]: ...

def expand(input_: Any, options: dict[str, Any] | None = ...) -> list[dict[str, Any]]: ...
def compact(input_: Any, ctx: Any, options: dict[str, Any] | None = ...) -> dict[str, Any]: ...
def get_document_loader() -> Callable[..., dict[str, Any]]: ...
def set_document_loader(loader: Callable[..., dict[str, Any]]) -> None: ...
