"""OSM road centrelines per ward -> public/heat-map/data/{ward}-roads.json.

WHY THIS EXISTS (2026-10-02). The three Kolkata roads artefacts were committed
with the heat map on 2026-07-24 WITHOUT the script that made them -- a standing
debt that fetch-water.py and fetch-road-labels.py both name. Ballygunge's move to
the KMC Ward 68 square needed new roads, so the generator had to exist, and it
had to reproduce the CONTRACT the renderer and the simulation already read:

    {"ward", "count", "source": "OpenStreetMap via Overpass (ODbL)",
     "ways": [{"w": 1 | 2, "p": [x0, y0, x1, y1, ...]}]}

in ward-local metres (x east, y NORTH, `_types.m_per_deg` about the ward centre),
0.5 m steps. `w` is not cosmetic: heat-map-model.ts turns `w > 1` into a 2-cell
tree-planting corridor and `w == 1` into a 1-cell one, which feeds corridorKm,
corridorSorted and the published tree, cost and cooling figures.

THE RULES BELOW WERE RECOVERED FROM THE COMMITTED FILES, NOT CHOSEN. A fresh
Overpass survey of every highway way over the old 1400 m Ballygunge window and
the Barrackpore window (2026-10-02) was matched vertex-for-vertex (0.5 m
rounding) against the committed artefacts: 500 of 500 Ballygunge ways and every
Barrackpore way matched an OSM way. What they show:

  * w = 2  primary, secondary          (motorway/trunk added by analogy; none occur)
  * w = 1  tertiary, unclassified, residential, service, living_street
           -- TERTIARY IS w = 1. fetch-road-labels.py LABELS tertiary as a major
           class; the drawn width table never did, and it is the width that
           reaches the physics, so it is reproduced as found.
  * NOT drawn: footway, cycleway, path, and the *_link ramps. None of the 1,032
    committed ways in the two wards is one, while the fresh survey holds 5
    footways, 2 cycleways, a path and 4 links in the same windows. (Whether the
    links existed in July is unknowable from here; leaving them out is the
    reproduction, not a judgement about them.)
  * CLIPPING IS BY VERTEX: a way keeps the vertices with |x| and |y| within the
    clip box (`_types.osm_clip_m`, 760 m at 1400 m) and survives if two remain.
    Every partial committed way has exactly its in-box vertex count, and only 2
    committed vertices sit ON the 760 m line -- a segment clip would put one on
    the line for every way that crosses it.
  * ORDER is Overpass's (ascending way id), which is what the committed rows
    follow apart from ways OSM has since split.

REPRODUCTION, MEASURED. Run over the fresh survey in the OLD frames, this script
regenerates 501 Ballygunge ways against the committed 500, 496 of them
vertex-for-vertex identical, and 532 Barrackpore ways against 532, 529 identical;
width classes agree on every identical way, and the major counts match exactly
(45 and 38). The residue is OSM's own edits since July.

The fresh survey has 535 ways where the committed file has 500: OSM changed in
two months, and that delta (mostly new residential and service ways) is the
reason the other two wards are NOT regenerated by default -- it would move their
corridor figures for no reason but OSM's own edits.

    python3 scripts/fetch-roads.py --ward ballygunge
    python3 scripts/fetch-roads.py --check     # asserts over the committed files, offline
"""
from __future__ import annotations

import argparse
import json
import os
import sys
import time
from typing import Any, cast

import requests

HERE = os.path.dirname(os.path.abspath(__file__))
if HERE not in sys.path:
    sys.path.insert(0, HERE)

import _types  # noqa: E402  (path first — scripts are not a package)

ROOT = os.path.join(HERE, "..")
OUT_DIR = os.path.join(ROOT, "public", "heat-map", "data")
SOURCE = "OpenStreetMap via Overpass (ODbL)"

#: Same mirrors, in the same order, as fetch-road-labels.py.
OVERPASS_ENDPOINTS = (
    "https://overpass-api.de/api/interpreter",
    "https://overpass.kumi.systems/api/interpreter",
    "https://overpass.private.coffee/api/interpreter",
)

#: Drawn as majors (road-ribbon.ts's 14 m, the model's 2-cell corridor).
MAJOR = ("motorway", "trunk", "primary", "secondary")
#: Drawn as minors (4 m, 1-cell corridor).
MINOR = ("tertiary", "unclassified", "residential", "service", "living_street")

#: 0.5 m: the step every committed vertex sits on.
STEP_M = 0.5


def width_class(highway: str) -> int:
    return 2 if highway in MAJOR else 1


def query(ward: _types.Ward) -> dict[str, Any]:
    w, s, e, n = _types.ward_bounds(ward, pad_m=_types.OSM_CLIP_PAD_M)
    classes = "|".join(MAJOR + MINOR)
    q = f"""[out:json][timeout:120];
way["highway"~"^({classes})$"]({s},{w},{n},{e});
out tags geom;"""
    last = ""
    for attempt in range(3):
        for url in OVERPASS_ENDPOINTS:
            try:
                r = requests.post(url, data=q.encode(),
                                  headers={"User-Agent": "delta-climate-research roads fetch"},
                                  timeout=180)
            except requests.RequestException as exc:
                last = f"{url}: {type(exc).__name__}"
                continue
            if r.status_code == 200 and r.text.lstrip().startswith("{"):
                return cast(dict[str, Any], r.json())
            last = f"{url}: HTTP {r.status_code}"
        time.sleep(20 * (attempt + 1))
    sys.exit(f"  every Overpass mirror failed for {ward.id} — last: {last}")


def snap(v: float) -> float:
    return round(v / STEP_M) * STEP_M


def build(ward: _types.Ward, data: dict[str, Any]) -> dict[str, Any]:
    mx, my = _types.m_per_deg(ward.centre.lat)
    clip = _types.osm_clip_m(ward)
    ways: list[tuple[int, dict[str, Any]]] = []
    for el in data.get("elements", []):
        if el.get("type") != "way":
            continue
        highway = el.get("tags", {}).get("highway", "")
        if highway not in MAJOR + MINOR:
            continue
        flat: list[float] = []
        for g in el.get("geometry") or []:
            x = snap((g["lon"] - ward.centre.lon) * mx)
            y = snap((g["lat"] - ward.centre.lat) * my)
            if abs(x) <= clip and abs(y) <= clip:
                flat += [x, y]
        if len(flat) >= 4:
            ways.append((int(el["id"]), {"w": width_class(highway), "p": flat}))
    ways.sort(key=lambda t: t[0])
    return {"ward": ward.id, "count": len(ways), "source": SOURCE,
            "ways": [w for _, w in ways]}


def out_path(ward_id: str) -> str:
    return os.path.join(OUT_DIR, f"{ward_id}-roads.json")


def check() -> int:
    bad = 0
    for ward in _types.WARDS.values():
        path = out_path(ward.id)
        if not os.path.exists(path):
            print(f"  MISSING {os.path.relpath(path, ROOT)}"); bad += 1; continue
        with open(path, encoding="utf-8") as fh:
            doc = json.load(fh)
        clip = _types.osm_clip_m(ward)
        problems = []
        if doc.get("ward") != ward.id:
            problems.append(f"ward {doc.get('ward')!r}")
        if doc.get("source") != SOURCE:
            problems.append(f"source {doc.get('source')!r}")
        if doc.get("count") != len(doc.get("ways", [])):
            problems.append("count disagrees with ways")
        for way in doc.get("ways", []):
            p = way.get("p", [])
            if way.get("w") not in (1, 2):
                problems.append(f"width class {way.get('w')!r}"); break
            if len(p) < 4 or len(p) % 2:
                problems.append("malformed way"); break
            if any(abs(v) > clip + 1e-9 for v in p):
                problems.append(f"vertex escapes the {clip:.0f} m clip box"); break
            if any(abs(v / STEP_M - round(v / STEP_M)) > 1e-9 for v in p):
                problems.append(f"vertex off the {STEP_M} m step"); break
        majors = sum(1 for w in doc.get("ways", []) if w.get("w") == 2)
        if not problems and not 0 < majors < doc["count"]:
            problems.append(f"{majors} major ways of {doc['count']} -- the class split is gone")
        if problems:
            print(f"  {ward.id}: FAIL — {'; '.join(problems)}"); bad += 1
        else:
            print(f"  {ward.id}: {doc['count']} ways ({majors} major) within ±{clip:.0f} m — ok")
    return bad


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--check", action="store_true",
                    help="assert over the committed artefacts, without fetching")
    ap.add_argument("--ward", choices=sorted(_types.WARDS), default=None,
                    help="the ward to fetch; omitting it fetches all three, which also "
                         "moves the two wards whose OSM has drifted since July")
    args = ap.parse_args()
    if args.check:
        return 1 if check() else 0
    os.makedirs(OUT_DIR, exist_ok=True)
    for ward in ([_types.WARDS[args.ward]] if args.ward else _types.WARDS.values()):
        doc = build(ward, query(ward))
        with open(out_path(ward.id), "w", encoding="utf-8") as fh:
            fh.write(json.dumps(doc, separators=(",", ":")))
        print(f"  {os.path.relpath(out_path(ward.id), ROOT)}  {doc['count']} ways  "
              f"{os.path.getsize(out_path(ward.id)) / 1024:.1f} KB")
        time.sleep(2)
    return 1 if check() else 0


if __name__ == "__main__":
    raise SystemExit(main())
